spring.application.name=joe.coffee.api
server.port=8080

# Configuration de la bdd
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:./data/joeCoffee.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.foreign_keys=true

#Chargemement des données
# Indique à Spring Boot de chercher le fichier data.sql et de l?exécuter
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=file:./data/data.sql

# Niveaux de log
logging.level.com.joe.coffee.api=DEBUG
logging.level.org.springframework=INFO
logging.level.root=INFO

# Format console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ? Fichier de log
logging.file.name=logs/joecoffee.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.file.append=true

# Optionnel : pattern de log pour le fichier (sinon reprend le pattern console)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# application.properties scan du package des Controller
springdoc.packages-to-scan=com.joe.coffee.api.Controller

